spring:
  datasource:
    url: jdbc:h2:mem:h2_database
    username: admin
    password: admin
    driver-class-name: org.h2.Driver
    initialization-mode: ALWAYS
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2
server:
  port: 8181
  error:
    whitelabel:
      enabled: false
